### ISSUE TITLE
Vue framework is in devDependencies

### ISSUE THREAD

**Issue by clemp6r** [alex8088/electron-vite-boilerplate#10]
Hi, can you explain why application frameworks like `vue` or `electron` are listed in `devDependencies` instead of `dependencies`? That seem a bit unexpected.

Thanks

**Comment by alex8088** [comment]
Frameworks like vue are used for rendering process development. For renderers, it is usually `fully bundle`, so dependencies are best installed in devDependencies. This makes the final package more smaller.
More detail: https://electron-vite.org/guide/dev.html#dependencies-vs-devdependencies

Also read https://electron-vite.org to learn more about `electron-vite`.

**Comment by clemp6r** [comment]
Thanks!
