### ISSUE TITLE
mac m1电脑 运行build:mac报错

### ISSUE THREAD

**Issue by rlinhe** [alex8088/electron-vite-boilerplate#4]

**Comment by rlinhe** [comment]
![image](https://user-images.githubusercontent.com/12096578/193537614-dfc58ee6-1cdc-48d4-9c9b-54c66923d2fd.png)

**Comment by alex8088** [comment]
需要安装Python3

**Comment by rlinhe** [comment]
> 
电脑里有python3, 对版本有特殊要求吗？
![image](https://user-images.githubusercontent.com/12096578/193539511-bce5eb75-f86f-41c3-9457-7807d9f32b40.png)

**Comment by alex8088** [comment]
是不是同时存在py2， https://github.com/electron-userland/electron-builder/issues/6873

**Comment by rlinhe** [comment]
> 是不是同时存在py2， [electron-userland/electron-builder#6873](https://github.com/electron-userland/electron-builder/issues/6873)

没有py2
![image](https://user-images.githubusercontent.com/12096578/193542116-ffeedee7-80da-4efa-9f13-f25e8fc6242d.png)

**Comment by alex8088** [comment]
你electron-builder 什么版本，是不是刚刚升级了macos，把electron-builder 升级最新版本

**Comment by rlinhe** [comment]
> 你electron-builder 什么版本，是不是刚刚升级了macos，把electron-builder 升级最新版本

"electron-builder": "^22.14.13", 和你现在仓库中的一样。

**Comment by alex8088** [comment]
升级一下electron-builder版本，可能是macOS更新导致，electron-builder新地版本会兼容

**Comment by rlinhe** [comment]
> 升级一下electron-builder版本，可能是macOS更新导致，electron-builder新地版本会兼容

electron-builder升级到 "electron-builder": "^23.5.1", build不报错了。但是安装运行，这样
![image](https://user-images.githubusercontent.com/12096578/193547116-90240410-8419-44e0-a0b4-5db6c50c08e5.png)

**Comment by Beiluola** [comment]
能否升级下模版`yarn create @quick-start/electron my-app --template vue`中`electron-builder`的依赖版本？今天下了个模版因为这个依赖搞了好久
