### ISSUE TITLE
Suggestion for an electron-vite-boilerplate-lit

### ISSUE THREAD

**Issue by rudifa** [alex8088/electron-vite-boilerplate#5]
Hello @alex8088

I was looking for help in creating an Electron app managed by Vite and using [Lit](https://lit.dev/docs/) components, and I found this repo, which uses Vue components.

I cloned your `electron-vite-boilerplate` and I ran successfully the resulting Vue app (both `dev` and `build:mac`).

I congratulate you for the nice clean project, which runs without any problems.

Since I have more experience with Lit than with Vue, React, Svelte, Solid, e.t.c., I tried (and succeeded) to transform your project into my [electron-vite-boilerplate-lit](https://github.com/rudifa/electron-vite-boilerplate-lit), which I just published on github.

I preserved the project code structure, but I replaced the Vite support and components by the similar Lit support and components.

Now, could you please look at my project and comment on it?
Then, if you find it interesting and useful, would you consider **adding a fork or clone of my project to your repo**, for better visibility? You would be welcome to modify and improve it, as you would see fit.

I also looked at you collection of templates in your [quick-start...create-electron](https://github.com/alex8088/quick-start/tree/master/packages/create-electron), and I created a couple of test projects (a vanilla and a vue project). These also ran without any problems.

My alternate or additional suggestion would be to **add the `lit` and `lit-ts` templates to your collection**. I am sure that this would be easy to do for you, as you know your workflow for adding and testing these templates.

Please let me know what you think of my suggestions.

Best regards, @rudifa

**Comment by alex8088** [comment]
Hi, @rudifa 

Thanks for your interest and suggestions in this project. I reviewed your project and made a [PR](https://github.com/rudifa/electron-vite-boilerplate-lit/pull/2). Regarding `create-electron` support for `it` and `lit-ts` templates, maybe it will be implemented in a future version. 

If you have any questions, you can submit a new issue at any time.
