### ISSUE TITLE
Vue router + electron vite

### ISSUE THREAD

**Issue by mb-mysterdev** [alex8088/electron-vite-boilerplate#7]
Hello Alex,
First of all, thank you for the work you have done. your repo is the best for the electron part with vite and vuejs.

But just a question when I configure the Router vuejs and I build it does not work knowing that by doing a yarn dev it works very well.

it works with yarn start and yarn dev but it doesn't work after build (linux).
I don't get any error but anything related to router-view or router link doesn't work

do you have an idea ? thank you

**Comment by alex8088** [comment]
@mb-mysterdev 

for production:

``` js
mainWindow.loadFile(path.join(__dirname, '../renderer/index.html'), { hash: '/main' })
```

**Comment by mb-mysterdev** [comment]
thank you, it works

**Comment by Abolfazl2049** [comment]
> thank you, it works

hey ,
im having problem with making a multiple page app.
can you explain how did you configured vue-router ?
thank you
